Advanced-Building-Blocks--Enumerables
Davidosky007/Advanced-Building-Blocks--Enumerables pull request #1
Opened 2020-11-05 10:34 UTC by Davidosky007

# Advanced-Building-Blocks--Enumerable
in this project we
- we used the module keyword
- Creating enumerable methods accepting a block using yield() and #call

2020-11-05 10:50 UTC, mahmoud717 requested changes
### Changes required ♻️ 
**Hi @Davidosky007 & @uchennaanya**
Great job with the project so far, but, there are still some changes to be made.
---
### Requested 🔴 
- please move all the test code from the main file into a test file
- please check the inline comments.
---
please make all the changes requested and file for another code review.

2020-11-05 10:50 UTC, mahmoud717 commented on main.rb
> +  end
- my_each when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- my_each when a block is given when self is a hash behaves like #each calls the given block once for each element in self

2020-11-05 10:50 UTC, mahmoud717 commented on main.rb
> +  end
- my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self

2020-11-05 10:50 UTC, mahmoud717 commented on main.rb
> +  end
- my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric

2020-11-05 10:50 UTC, mahmoud717 commented on main.rb
> +  end
- my_any? when no block or argument is given returns false if at least one of the collection is not true
- my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric

2020-11-05 10:50 UTC, mahmoud717 commented on main.rb
> +    end
- my_none? when no block or argument is given returns true only if none of the collection members is true
- my_none? when no block or argument is given returns false only if one of the collection members is true

2020-11-05 10:50 UTC, mahmoud717 commented on main.rb
> +end
- my_inject raises a "LocalJumpError" when no block or argument is given

2020-11-06 18:56 UTC, ElijahTobs approved these changes
# Status: Approved! :tada: 

## Congratulations! @Davidosky007 and @uchennaanya  

 Good job implementing the changes requested by the previous TSE.

### Before you merge and submit, make sure you work on the link to the live demo in your README.md file. In this case, you're expected to have a link to an online IDE like [repl](https://repl.it) that contains your code.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2020-11-07 03:27 UTC, merged